steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/project-id/image:tag", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/project-id/image:tag"]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=weather-app-deployment.yaml
  - --image=gcr.io/project-id/image:tag
  - --location=us-central1-c
  - --cluster=cluster-1
